/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Group8_Final;

import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JComboBox;


public class OrderDashboard extends javax.swing.JFrame {

    /**
     * Creates new form OrderDashboard
     */
    public OrderDashboard() {
        initComponents();
        CHECKOUT.setEnabledAt(1, false); 
        this.setLocationRelativeTo(null);
    }

    public class UserDetailsSaver {

    private static final String FILE_PATH = "C:\\Users\\sagui\\OneDrive\\Desktop\\PlayerDetails.txt";

   
    public static void saveUserDetails(String ign, String id, String selectedGame) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH, true))) {
            writer.write("In-Game Name: " + ign);
            writer.newLine();
            writer.write("User ID: " + id);
            writer.newLine();
            writer.write("Selected Game: " + selectedGame);
            writer.newLine();
            writer.write("---------------------------");
            writer.newLine();
            
            JOptionPane.showMessageDialog(null, "Details saved successfully!");
            } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error saving details.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
        public void updatePriceComboBoxes(List<String> selectedGames) {
    
        GamePrices1.removeAllItems();
        GamePrices2.removeAllItems();
        GamePrices3.removeAllItems();

    // Helper method to add prices for each combo box based on game
    addPriceOptions(GamePrices1, selectedGames.size() > 0 ? selectedGames.get(0) : null);
    addPriceOptions(GamePrices2, selectedGames.size() > 1 ? selectedGames.get(1) : null);
    addPriceOptions(GamePrices3, selectedGames.size() > 2 ? selectedGames.get(2) : null);

    GamePrices1.setEnabled(selectedGames.size() >= 0);
    GamePrices2.setEnabled(selectedGames.size() >= 1);
    GamePrices3.setEnabled(selectedGames.size() >= 2);
}

// Extracted reusable method to add price items to a JComboBox
    private void addPriceOptions(JComboBox<String> comboBox, String game) {
    comboBox.removeAllItems();

    if (game == null) {
        comboBox.setEnabled(false);
        return;
    }

    comboBox.setEnabled(true);

    switch (game) {
        case "Mobile Legends":
            comboBox.addItem("50 Php - 60 Diamonds");
            comboBox.addItem("100 Php - 150 Diamonds");
            comboBox.addItem("200 Php - 300 Diamonds");
            comboBox.addItem("500 Php - 750 Diamonds");
            break;
        case "Call of Duty Mobile":
            comboBox.addItem("50 Php - 80 CP");
            comboBox.addItem("115 Php - 200 CP");
            comboBox.addItem("250 Php - 600 CP");
            comboBox.addItem("500 Php - 1500 CP");
            break;
        case "Valorant":
            comboBox.addItem("60 Php - 110 VP");
            comboBox.addItem("150 Php - 225 VP");
            comboBox.addItem("200 Php - 300 VP");
            comboBox.addItem("500 Php - 1200 VP");
            break;
        case "PUBG":
            comboBox.addItem("50 Php - 90 UC");
            comboBox.addItem("75 Php - 190 UC");
            comboBox.addItem("120 Php - 250 UC");
            comboBox.addItem("300 Php - 700 UC");
            break;
        case "Genshin Impact":
            comboBox.addItem("50 Php - 80 Primogems");
            comboBox.addItem("100 Php - 160 Primogems");
            comboBox.addItem("250 Php - 499 Primogems");
            comboBox.addItem("500 Php - 1200 Primogems");
            break;
        case "Call of Duty: Warzone":
            comboBox.addItem("80 Php - 120 CP");
            comboBox.addItem("150 Php - 270 CP");
            comboBox.addItem("300 Php - 600 CP");
            comboBox.addItem("700 Php - 1500 CP");
            break;
        default:
            comboBox.addItem("No price options available");
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGroupgames = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BackDashboard = new javax.swing.JButton();
        LoggingOut = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        CHECKOUT = new javax.swing.JTabbedPane();
        gameselection = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MLch = new javax.swing.JCheckBox();
        codmch = new javax.swing.JCheckBox();
        genshinch = new javax.swing.JCheckBox();
        pubgch = new javax.swing.JCheckBox();
        valoch = new javax.swing.JCheckBox();
        warzonech = new javax.swing.JCheckBox();
        Proceed2ChooseAmount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserDetails = new javax.swing.JPanel();
        Pdetails = new javax.swing.JLabel();
        IngameName = new javax.swing.JTextField();
        UserId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JTextField();
        chooseAmount = new javax.swing.JPanel();
        checkingoutdash = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        design = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PaymentMethod = new javax.swing.JComboBox<>();
        finalize = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        GamePrices1 = new javax.swing.JComboBox<>();
        GamePrices2 = new javax.swing.JComboBox<>();
        GamePrices3 = new javax.swing.JComboBox<>();
        codmCO = new javax.swing.JPanel();
        OrderSum = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        ReceiptArea = new java.awt.TextArea();
        NewOrderBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        BackDashboard.setBackground(new java.awt.Color(204, 204, 204));
        BackDashboard.setText("Go back to Menu Dashboard");
        BackDashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.gray));
        BackDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackDashboardMouseClicked(evt);
            }
        });

        LoggingOut.setBackground(new java.awt.Color(255, 153, 153));
        LoggingOut.setText("Log Out");
        LoggingOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.red, java.awt.Color.pink, java.awt.Color.white));
        LoggingOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoggingOutMouseClicked(evt);
            }
        });

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group8_Final/TopUpZone_logo_new_135x105.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(LoggingOut, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoggingOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CHECKOUT.setBackground(new java.awt.Color(255, 255, 204));

        gameselection.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));

        MLch.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        MLch.setText("Mobile Legends: Bang Bang");

        codmch.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        codmch.setText("Call of Duty: Mobile");

        genshinch.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        genshinch.setText("Genshin Impact");

        pubgch.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        pubgch.setText("Player Unknown's BattleGrounds");

        valoch.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        valoch.setText("Valorant: Shooting Game");

        warzonech.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        warzonech.setText("Call of Duty: Warzone");

        Proceed2ChooseAmount.setBackground(new java.awt.Color(204, 255, 204));
        Proceed2ChooseAmount.setText("Proceed to Choose Amount");
        Proceed2ChooseAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Proceed2ChooseAmountMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("SELECT YOUR DESIRED GAME BELOW AND PROCEED TO TOP UP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(MLch)
                    .addComponent(genshinch)
                    .addComponent(valoch)
                    .addComponent(warzonech)
                    .addComponent(codmch)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Proceed2ChooseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pubgch)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(MLch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codmch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genshinch)
                .addGap(18, 18, 18)
                .addComponent(pubgch)
                .addGap(18, 18, 18)
                .addComponent(valoch)
                .addGap(12, 12, 12)
                .addComponent(warzonech)
                .addGap(47, 47, 47)
                .addComponent(Proceed2ChooseAmount)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        UserDetails.setBackground(new java.awt.Color(255, 204, 204));
        UserDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 7));

        Pdetails.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Pdetails.setText("Player Account Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Enter your Ingame Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Enter your UID (Server ID)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Enter your Phone Number");

        javax.swing.GroupLayout UserDetailsLayout = new javax.swing.GroupLayout(UserDetails);
        UserDetails.setLayout(UserDetailsLayout);
        UserDetailsLayout.setHorizontalGroup(
            UserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserDetailsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(UserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserId, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(IngameName)
                    .addGroup(UserDetailsLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Pdetails))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        UserDetailsLayout.setVerticalGroup(
            UserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserDetailsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Pdetails)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IngameName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gameselectionLayout = new javax.swing.GroupLayout(gameselection);
        gameselection.setLayout(gameselectionLayout);
        gameselectionLayout.setHorizontalGroup(
            gameselectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameselectionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(UserDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        gameselectionLayout.setVerticalGroup(
            gameselectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameselectionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(gameselectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CHECKOUT.addTab("       Game Selection       ", gameselection);

        chooseAmount.setBackground(new java.awt.Color(204, 204, 204));
        chooseAmount.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jLabel6.setText("Select your Payment Method");

        PaymentMethod.setBackground(new java.awt.Color(255, 204, 204));
        PaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GCash", "Maya", "Regular Load Balance", "Bank Account", "PayPal" }));
        PaymentMethod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 6));

        javax.swing.GroupLayout designLayout = new javax.swing.GroupLayout(design);
        design.setLayout(designLayout);
        designLayout.setHorizontalGroup(
            designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(designLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(PaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        designLayout.setVerticalGroup(
            designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        finalize.setBackground(new java.awt.Color(204, 255, 204));
        finalize.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        finalize.setText("Finalize Order");
        finalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jLabel4.setText("Choose the amount of the selected games");

        GamePrices1.setBackground(new java.awt.Color(255, 204, 204));
        GamePrices1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        GamePrices1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GamePrices1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 6, true));

        GamePrices2.setBackground(new java.awt.Color(255, 204, 204));
        GamePrices2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        GamePrices2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GamePrices2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 6, true));

        GamePrices3.setBackground(new java.awt.Color(255, 204, 204));
        GamePrices3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        GamePrices3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GamePrices3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 6, true));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GamePrices1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GamePrices2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GamePrices3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(finalize, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GamePrices1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GamePrices2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GamePrices3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(finalize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout checkingoutdashLayout = new javax.swing.GroupLayout(checkingoutdash);
        checkingoutdash.setLayout(checkingoutdashLayout);
        checkingoutdashLayout.setHorizontalGroup(
            checkingoutdashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkingoutdashLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        checkingoutdashLayout.setVerticalGroup(
            checkingoutdashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkingoutdashLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        chooseAmount.add(checkingoutdash, "card2");

        javax.swing.GroupLayout codmCOLayout = new javax.swing.GroupLayout(codmCO);
        codmCO.setLayout(codmCOLayout);
        codmCOLayout.setHorizontalGroup(
            codmCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        codmCOLayout.setVerticalGroup(
            codmCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        chooseAmount.add(codmCO, "card3");

        CHECKOUT.addTab("       Choose Amount       ", chooseAmount);

        OrderSum.setBackground(new java.awt.Color(204, 204, 255));

        ReceiptArea.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        scrollPane1.add(ReceiptArea);

        NewOrderBtn.setBackground(new java.awt.Color(0, 255, 255));
        NewOrderBtn.setText("Place New Order");
        NewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderSumLayout = new javax.swing.GroupLayout(OrderSum);
        OrderSum.setLayout(OrderSumLayout);
        OrderSumLayout.setHorizontalGroup(
            OrderSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderSumLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(NewOrderBtn)
                .addGap(14, 14, 14))
        );
        OrderSumLayout.setVerticalGroup(
            OrderSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderSumLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(OrderSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderSumLayout.createSequentialGroup()
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderSumLayout.createSequentialGroup()
                        .addComponent(NewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
        );

        CHECKOUT.addTab("       Order Summary       ", OrderSum);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CHECKOUT))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CHECKOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackDashboardMouseClicked
        Menu_Dashboard dashb = new Menu_Dashboard();
        dashb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackDashboardMouseClicked

    private void LoggingOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoggingOutMouseClicked
        LogInDashboard logind = new LogInDashboard();
        logind.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoggingOutMouseClicked

    private void Proceed2ChooseAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proceed2ChooseAmountMouseClicked
         System.out.println("Proceed button clicked");
    
    String ign = IngameName.getText().trim();
    String id = UserId.getText().trim();
    String phone = PhoneNumber.getText().trim();
    
    if (ign.isEmpty() || id.isEmpty() || phone.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter your IGN, User ID, and Phone Number.");
    return;
}

        List<String> selectedGames = new ArrayList<>();
    if (MLch.isSelected()) selectedGames.add("Mobile Legends");
    if (codmch.isSelected()) selectedGames.add("Call of Duty Mobile");
    if (valoch.isSelected()) selectedGames.add("Valorant");
    if (pubgch.isSelected()) selectedGames.add("PUBG");
    if (genshinch.isSelected()) selectedGames.add("Genshin Impact");
    if (warzonech.isSelected()) selectedGames.add("Call of Duty: Warzone");

    System.out.println("Selected games count: " + selectedGames.size());

    if (selectedGames.size() == 0 || selectedGames.size() > 3) {
        JOptionPane.showMessageDialog(null, "Please select 1 to 3 games only.");
        return;
    }

    // Save details if needed
    for (String game : selectedGames) {
        UserDetailsSaver.saveUserDetails(ign, id, game);
    }

    updatePriceComboBoxes(selectedGames);

    CHECKOUT.setEnabledAt(1, true);   // enable tab 1
    CHECKOUT.setSelectedIndex(1);     // switch to tab 1 
    }//GEN-LAST:event_Proceed2ChooseAmountMouseClicked

    private void finalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeActionPerformed
         String ign = IngameName.getText().trim();
         String id = UserId.getText().trim();
         String phone = PhoneNumber.getText().trim();
         String payment = (String) PaymentMethod.getSelectedItem();

        if (phone.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter your phone number.");
    return;
}

    if (payment == null || payment.equals("Select...")) {
    JOptionPane.showMessageDialog(this, "Please select a payment method.");
    return;
}


    if (ign.isEmpty() || id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your IGN and User ID.");
        return;
    }

    // Collect selected games
    List<String> selectedGames = new ArrayList<>();
    if (MLch.isSelected()) selectedGames.add("Mobile Legends");
    if (codmch.isSelected()) selectedGames.add("Call of Duty Mobile");
    if (valoch.isSelected()) selectedGames.add("Valorant");
    if (pubgch.isSelected()) selectedGames.add("PUBG");
    if (genshinch.isSelected()) selectedGames.add("Genshin Impact");
    if (warzonech.isSelected()) selectedGames.add("Call of Duty: Warzone");

    // Collect prices only matching the number of selected games
    List<String> selectedPrices = new ArrayList<>();
    for (int i = 0; i < selectedGames.size(); i++) {
        switch (i) {
            case 0: selectedPrices.add((String) GamePrices1.getSelectedItem()); break;
            case 1: selectedPrices.add((String) GamePrices2.getSelectedItem()); break;
            case 2: selectedPrices.add((String) GamePrices3.getSelectedItem()); break;
        }
    }

    int total = 0;

    StringBuilder receipt = new StringBuilder();
    receipt.append("YOUR RECEIPT\n\n");
    receipt.append("In-Game Name: ").append(ign).append("\n");
    receipt.append("User ID: ").append(id).append("\n\n");
    receipt.append("Phone Number: ").append(phone).append("\n");
    receipt.append("Payment Method: ").append(payment).append("\n\n");


    for (int i = 0; i < selectedGames.size(); i++) {
        String game = selectedGames.get(i);
        String price = selectedPrices.get(i);
        int amount = extractAmount(price);
        total += amount;

        // Save to file (your method currently saves without price)
        UserDetailsSaver.saveUserDetails(ign, id, game);

        receipt.append("Game: ").append(game).append("\n");
        receipt.append("Selected Price: ").append(price).append("\n\n");
    }

    receipt.append("TOTAL AMOUNT: ").append(total).append(" PHP\n\n");
    receipt.append("✅ Thank you for using TopUpZone!\n");
    receipt.append("Your order has been processed.\n");
    receipt.append("For inquiries, contact: support@topupzone.com / 0948-020-0768");

    // Show in Tab 3
    ReceiptArea.setText(receipt.toString());

    // Proceed to Order Summary tab
    CHECKOUT.setEnabledAt(2, true);
    CHECKOUT.setSelectedIndex(2);

    JOptionPane.showMessageDialog(this, "Finalized! Total: " + total + " PHP");
    }//GEN-LAST:event_finalizeActionPerformed

    private void NewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Start a new order?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        // Clear IGN and User ID
        IngameName.setText("");
        UserId.setText("");

        // Clear selected checkboxes
        MLch.setSelected(false);
        codmch.setSelected(false);
        genshinch.setSelected(false);
        pubgch.setSelected(false);
        valoch.setSelected(false);
        warzonech.setSelected(false);

        // Reset price combo boxes
        GamePrices1.removeAllItems();
        GamePrices2.removeAllItems();
        GamePrices3.removeAllItems();
        GamePrices1.setEnabled(false);
        GamePrices2.setEnabled(false);
        GamePrices3.setEnabled(false);

        // Clear receipt area
        ReceiptArea.setText("");

        // Disable Tabs 2 and 3 again
        CHECKOUT.setEnabledAt(1, false);
        CHECKOUT.setEnabledAt(2, false);

        // Go back to Tab 0
        CHECKOUT.setSelectedIndex(0);
    }
    }//GEN-LAST:event_NewOrderBtnActionPerformed
    
     private int extractAmount(String priceStr) {
    if (priceStr == null || !priceStr.contains("Php")) return 0;
    try {
        return Integer.parseInt(priceStr.split("Php")[0].trim());
    } catch (NumberFormatException e) {
        return 0;
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGroupgames;
    private javax.swing.JButton BackDashboard;
    private javax.swing.JTabbedPane CHECKOUT;
    private javax.swing.JComboBox<String> GamePrices1;
    private javax.swing.JComboBox<String> GamePrices2;
    private javax.swing.JComboBox<String> GamePrices3;
    private javax.swing.JTextField IngameName;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton LoggingOut;
    private javax.swing.JCheckBox MLch;
    private javax.swing.JButton NewOrderBtn;
    private javax.swing.JPanel OrderSum;
    private javax.swing.JComboBox<String> PaymentMethod;
    private javax.swing.JLabel Pdetails;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JButton Proceed2ChooseAmount;
    private java.awt.TextArea ReceiptArea;
    private javax.swing.JPanel UserDetails;
    private javax.swing.JTextField UserId;
    private javax.swing.JPanel checkingoutdash;
    private javax.swing.JPanel chooseAmount;
    private javax.swing.JPanel codmCO;
    private javax.swing.JCheckBox codmch;
    private javax.swing.JPanel design;
    private javax.swing.JButton finalize;
    private javax.swing.JPanel gameselection;
    private javax.swing.JCheckBox genshinch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JCheckBox pubgch;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JCheckBox valoch;
    private javax.swing.JCheckBox warzonech;
    // End of variables declaration//GEN-END:variables
}
